[package]
name = "minecraft-pixelart"
version = "0.1.0"
edition = "2025"

[dependencies]
image = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.7"
indicatif = "0.17"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1